version: '3.7'

services:
  db:
    image: postgres:15
    container_name: market_db
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: market_redis

  market:
    build:
      context: .
    image: market_image
    container_name: market_app
    env_file:
      - .env-non-dev
    ports:
      - "7777:8000"  # Теперь API доступно на localhost:9000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    command: ["sh", "/Market/docker/app.sh"]


  celery:
    image: market_celery
    build:
      context: .
    container_name: market_celery
    depends_on:
      redis:
        condition: service_started
    command: ["/Market/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev


  flower:
    image: market_flower
    build:
      context: .
    container_name: market_flower
    ports:
      - 5555:5555
    depends_on:
      redis:
        condition: service_started
    command: [ "/Market/docker/celery.sh", "flower" ]
    env_file:
      - .env-non-dev